### ISSUE TITLE
[WIP] RoadMap

### ISSUE THREAD

**Issue by luckylat** [luckylat/eddy#1]
TBD
## Feature
- [ ] impl simple text editor (just writing)
  - [ ] impl functions
    - [ ] tabbing
    - [ ] custom syntax highlight
    - [ ] base of plugin
  - [ ] impl subordinate plugins
    - [ ] filing
    - [ ] outline viewer
    - [ ] history
  - [ ] impl independent plugins
    - [ ] import from [mi](https://www.mimikaki.net/)
- [ ] Design
